config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :sessions, only: %i[new create destroy]
  resources :chats, only: %i[index show update destroy]
  resources :users do
    resources :messages, only: %i[index]
    get '/profile/edit', to: 'profiles#edit'
    patch '/profile', to: 'profiles#update'
  end
  get '/pages/privacy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: :User, inverse_of: :sent_messages
  belongs_to :receiver, class_name: :User, inverse_of: :received_messages

  scope :sent_and_received_messages, -> (user) do
  	where(
      'sender_id = ? OR receiver_id = ?',
      user.id,
      user.id
    ).order(created_at: :desc)
  end

  scope :chat, -> (user, chat_user) do
  	where(
      'sender_id = ? AND receiver_id = ? OR sender_id = ? AND receiver_id = ?',
      user.id,
      chat_user.id,
      chat_user.id,
      user.id
    ).order(created_at: :desc).limit(50).reverse
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, inverse_of: :profile

  validates :nickname, :user_id, presence: true
  validates :user_id, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many(
    :sent_messages,
    class_name: :Message,
    foreign_key: :sender_id,
    inverse_of: :sender,
    dependent: :destroy
  )
  has_many(
    :received_messages,
    class_name: :Message,
    foreign_key: :receiver_id,
    inverse_of: :receiver,
    dependent: :destroy
  )
  has_many(
    :sent_users,
    class_name: :User,
    foreign_key: :receiver_id,
    through: :sent_messages,
    source: :receiver
  )
  has_many(
    :received_users,
    class_name: :User,
    foreign_key: :sender_id,
    through: :received_messages,
    source: :sender
  )
  has_one :profile, dependent: :destroy, inverse_of: :user
  has_secure_password

  validates :email, :provider, :uid, presence: true
  validates :email, uniqueness: true, format: { with: /\A[\w.]+@\w+\.\w+\z/i }

  scope :with_profile, -> { joins(:profile).order(nickname: :asc) }

  def self.find_or_create_by_auth_hash(auth_hash)
    info = auth_hash[:info]
    user = User.find_or_create_by(email: info[:email])
    return user if user.update(
      uid: auth_hash[:uid],
      provider: auth_hash[:provider],
      password: SecureRandom.hex
    )

    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :verify_session_and_find_user

  def index
    @chat_users = (@user.sent_users + @user.received_users).uniq
  end

  def show
    @chat_user = User.find_by(id: params[:id])
    @messages = Message.chat(@user, @chat_user)
    @new_message = Message.new(sender: @user, receiver: @chat_user)
  end

  def update
    Message.create(message_params)
    redirect_to chat_path(params[:id])
  end

  private

  def message_params
    params.require(:message).permit(:body, :sender_id, :receiver_id)
  end

  def verify_session_and_find_user
    redirect_to root_path unless session[:id]
    @user = User.find(session[:id])
    redirect_to root_path unless @user.profile
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @user = User.find_by(id: params[:user_id])
    return redirect_to root_path unless @user.id == session[:id]

    @messages = Message.sent_and_received_messages(@user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def privacy; end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :find_user_and_profile
  before_action :verify_user

  def edit; end

  def update
    return render 'edit' unless @profile.update(profile_params)

    redirect_to user_path(@user)
  end

  private

  def profile_params
    params.require(:profile).permit(
      :nickname,
      :first_name,
      :middle_name,
      :last_name,
      :bio,
      :likes,
      :dislikes,
      :age,
      :user_id
    )
  end

  def find_user_and_profile
    @user = User.find(params[:user_id])
    @profile = Profile.find_or_create_by(user_id: @user.id) do |profile|
      profile.nickname = 'Unknown'
    end
  end

  def verify_user
    redirect_to root_path unless @user.id == session[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    if params[:provider] == 'none'
      @user = User.find_by(email: params[:email])
      return render 'new' unless @user&.authenticate(params[:password])

    else
      @user = User.find_or_create_by_auth_hash(auth_hash)
    end
    session[:id] = @user&.id
    return redirect_to user_path(@user) if @user

    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show edit update destroy]
  before_action :confirm_user, only: %i[edit update destroy]

  def index
    @users = User.with_profile
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.provider = 'none'
    @user.uid = SecureRandom.hex
    return render 'new' unless @user.save

    @user.update(uid: @user.id)
    session[:id] = @user.id
    redirect_to user_path(@user)
  end

  def edit; end

  def update
    return render 'edit' unless @user.update(user_params)

    @user.update(uid: @user.id, provider: 'none') unless @user.provider == 'none'
    redirect_to user_path(@user)
  end

  def destroy
    @user.destroy

    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def confirm_user
    redirect_to root_path unless @user&.id == session[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def unknown_if_nil(attribute)
    if attribute.nil?
      'Unknown'
    else
      attribute
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:id] && User.find_by(id: session[:id])
  end

  def current_user
    User.find_by(id: session[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_chat.html.erb
<div class='chat'>
	<% messages.each do |message| %>
		<p><%= "#{message.body} - #{message.sender.profile.nickname}" %><p>
	<% end %>
</div>

app/views/chats/index.html.erb
<h1>Current Chats:</h1>
<ul>
	<% @chat_users.each do |user| %>
		<li>
			<h3><%= user.profile.nickname %></h3>
			<p><%= link_to 'Profile', user_path(user) %></p>
			<p><%= link_to 'Message', chat_path(user) %></p>
		</li>
	<% end %>
</ul>

app/views/chats/show.html.erb
<div class="col">
	<%= render partial: 'chat', locals: { messages: @messages } %>
	<%= form_with model: @new_message, url: chat_path(@chat_user), method: 'PATCH' do |message| %>
		<%= message.hidden_field :sender_id %>
		<%= message.hidden_field :receiver_id %>
		<div class="input-group mb-3">
			<%= message.text_field :body, class: 'chat-input' %>
		</div>
		<div class="input-group-append">
			<%= message.submit 'Send', class: 'btn btn-primary chat-input' %>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheOne</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <%= render 'shared/navbar' %>
          <div class="my-3">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<%= render partial: 'chats/chat', locals: { messages: @messages } %>

app/views/pages/home.html.erb
<h1>Hello, and welcome to The One!</h1>
<h3>by Jade Masker</h3>
<p>
	Use the navbar above to navigate the site,
	select a user you think matches you,
	and just start chatting!
</p>

app/views/profiles/edit.html.erb
<h1>Edit Profile</h1>

<%= form_with model: @profile, url: user_profile_path(@profile.user), local: true do |profile| %>
	<%= render partial: 'shared/error', locals: { object: profile.object } %>
	<%= profile.label :nickname %>
	<%= profile.text_field :nickname %>
	<br>
	<%= profile.label :first_name, 'First Name' %>
	<%= profile.text_field :first_name %>
	<br>
	<%= profile.label :middle_name, 'Middle Name' %>
	<%= profile.text_field :middle_name %>
	<br>
	<%= profile.label :last_name, 'Last Name' %>
	<%= profile.text_field :last_name %>
	<br>
	<%= profile.label :bio %>
	<%= profile.text_area :bio %>
	<br>
	<%= profile.label :likes %>
	<%= profile.text_area :likes %>
	<br>
	<%= profile.label :dislikes %>
	<%= profile.text_area :dislikes %>
	<br>
	<%= profile.label :age %>
	<%= profile.number_field :age %>
	<br>
	<%= profile.submit %>
<% end %>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
	<ul>
		<% object.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
	<% unless logged_in? %>
		<%= link_to 'Login/Connect', new_session_path %>
		|
		<%= link_to 'Signup', new_user_path %>
	<% else %>
		<%= link_to "#{current_user.email} - Logout", session_path(current_user), method: :delete %>
		|
		<%= link_to 'Your Chats', chats_path %>
		|
		<%= link_to 'Your Profile', user_path(current_user) %>
	<% end %>
	|
	<%= link_to 'Home', root_path %>
	|
	<%= link_to 'Privacy Policy', pages_privacy_path %>
	|
	<%= link_to 'Users', users_path %>
</nav>

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |user| %>
	<%= render partial: 'shared/error', locals: { object: user.object } %>
	<%= user.label :email %>
	<%= user.email_field :email %>
	<br>
	<%= user.label :password %>
	<%= user.password_field :password %>
	<br>
	<%= user.label :password_confirmation, 'Please confirm new password:' %>
	<%= user.password_field :password_confirmation %>

	<%= user.submit class: 'btn btn-success' %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your credentials (can't undo!)</h1>
<%= render partial: 'form', locals: { user: @user } %>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
	<% @users.each do |user| %>
		<li>
			<%= link_to user.profile.nickname, user_path(user) %>
		</li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Create a new user</h1>
<%= render partial: 'form', locals: { user: @user } %>

app/views/users/show.html.erb
<% if logged_in? %>
	<% if current_user == @user %>
		<h1><%= @user.email %></h1>
		<p><%= "Provider: #{@user.provider}" %></p>
		<p><%= "UID: #{@user.uid}" %></p>
		<%= link_to 'Edit User Credentials', edit_user_path %>
		| <%= link_to 'Edit User Profile', user_profile_edit_path(current_user) %>
		| <%= link_to 'View All Messages', user_messages_path(current_user) %>
	<% else %>
		<%= link_to 'Chat with this user', chat_path(@user) %>
	<% end %>
<% end %>
<% if @user.profile %>
	<h2><%= @user.profile.nickname %></h2>
	<p><%= "First Name: #{unknown_if_nil(@user.profile.first_name)}" %></p>
	<p><%= "Middle Name: #{unknown_if_nil(@user.profile.middle_name)}" %></p>
	<p><%= "Last Name: #{unknown_if_nil(@user.profile.last_name)}" %></p>
	<p><%= "Bio: #{unknown_if_nil(@user.profile.bio)}" %></p>
	<p><%= "Likes: #{unknown_if_nil(@user.profile.likes)}" %></p>
	<p><%= "Dislikes: #{unknown_if_nil(@user.profile.dislikes)}" %></p>
	<p><%= "Age: #{unknown_if_nil(@user.profile.age)}" %></p>
<% end %>